apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base/machines/infra
- ../../base/machines
patchesStrategicMerge:
- patch-roles.yaml
- patch-replicas.yaml
- patch-hw.yaml
- patch-vmware.yaml
